### ISSUE TITLE
it.tdlight.client.TelegramError: 400: Chat not found

### ISSUE THREAD

**Issue by JavoxirJava** [laravel-notification-channels/telegram#187]
Exception in thread "main" java.util.concurrent.ExecutionException: it.tdlight.client.TelegramError: 400: Chat not found
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at it.tdlight.example.Example.main(Example.java:84)
Caused by: it.tdlight.client.TelegramError: 400: Chat not found
	at it.tdlight.client.SimpleTelegramClient.lambda$sendUnsafe$5(SimpleTelegramClient.java:379)
	at it.tdlight.InternalClient.handleResponse(InternalClient.java:99)
	at it.tdlight.InternalClient.handleEvent(InternalClient.java:117)
	at it.tdlight.InternalClient.handleEvents(InternalClient.java:71)
	at it.tdlight.ClientFactoryImpl.handleClientEvents(ClientFactoryImpl.java:87)
	at it.tdlight.ResponseReceiver.run(ResponseReceiver.java:113)

**Comment by irazasyed** [comment]
Wrong project. This is not a Java project.

**Comment by JavoxirJava** [comment]
Sorry, I didn't understand your answer well

**Comment by JavoxirJava** [comment]
![Uploading photo_2023-12-12_22-35-13.jpg…]()

**Comment by JavoxirJava** [comment]
![photo_2023-12-12_22-35-13](https://github.com/laravel-notification-channels/telegram/assets/100822200/55a1fb86-e60b-4bb9-b97c-aa0f89dc1cf8)
